### ISSUE TITLE
摸鱼插件无法使用。

### ISSUE THREAD

**Issue by Unword** [oflg/fishing-catchfish#12]
我并不清楚是哪里出了问题，只是希望能找到解决办法。

1.在墨屉手册里，下载的墨屉是无法使用选中句子添加记忆卡的。
但是墨屉手册是可以的。
我看了下，里面的插件都是都一个版本，基本无区别，但是一个能用，一个不能用。很奇怪。
而且两个在太记里面都无法使用。
2.有人说是Dynannotate 版本太新（比如5.30），导致选中的两个值
[$:/config/Dynannotate/LegacySelectionTracker/Enable](tidgi://UCjYCDUV063apTFfpd9uP#%24%3A%2Fplugins%2Ftiddlywiki%2Fdynannotate:%24%3A%2Fplugins%2Ftiddlywiki%2Fdynannotate%20%24%3A%2FControlPanel%20%E6%93%8D%E4%BD%9C)
[$:/config/Dynannotate/SelectionTracker/Enable](tidgi://UCjYCDUV063apTFfpd9uP#%24%3A%2Fplugins%2Ftiddlywiki%2Fdynannotate:%24%3A%2Fplugins%2Ftiddlywiki%2Fdynannotate%20%24%3A%2FControlPanel%20%E6%93%8D%E4%BD%9C)
默认是no，根据说明全改成yes也不行。
而最新墨屉里面是5.27版本的，之前是5.25版本的Dynannotate 和Dynaview。
3.单独安装所需插件，也是不行。钓鱼系列插件、Dynannotate 、Dynaview。

**Comment by oflg** [comment]
确实是因为Dynannotate插件5.3.0更新导致的，原因是更新后它将LegacySelectionTracker默认设置为了no。

解决方法是将`$:/config/Dynannotate/LegacySelectionTracker/Enable`中的值改为`yes`，后续（今天）我再更新，解决这个问题。

不清楚你那边改为`yes`为什么不行

**Comment by Unword** [comment]
但是不止是这个问题，问题在于下载的墨屉，也是不行的，无论用的是太记还是网页打开，而且版本是5.2.5或者5.2.7，或者我自己安装最新的，并且更改这两个值，都不行。
就墨屉手册那里可以，将手册下载过来网页打开是可以的，放到太记里面，是不行的。
我从官网下载空白文件，并且将两个插件和钓鱼系列插件从墨屉手册拖过来，当时版本还是5.2.5，也不行。
网页用的火狐和edge都试过。
这是否依赖于某个电脑环境，比如nodejs ？

**Comment by oflg** [comment]
> 问题在于下载的墨屉，也是不行的，无论用的是太记还是网页打开，而且版本是5.2.5或者5.2.7，或者我自己安装最新的，并且更改这两个值，都不行。
> 就墨屉手册那里可以，将手册下载过来网页打开是可以的，放到太记里面，是不行的。

我没法复现上面说的情况，刚刚[更新了一下](https://github.com/oflg/TiddlyMemo/releases/tag/v1.8.3)，尝试解决这个问题。

在插件里点击更新试试，如果还是不行，截下面这个图发出来看看是不是设置的问题。

![image](https://github.com/oflg/fishing-catchfish/assets/42492105/8186608a-2423-4e48-840a-1a8fb6446f82)

**Comment by Unword** [comment]
最新的墨屉手册我试过了，现在下载后在网页和太记都可以正常使用。
但是里面下载下来的墨屉还是不行。网页版不行，太记里也不行。
下载下来的墨屉截图已放
![屏幕截图 2023-09-07 215201](https://github.com/oflg/fishing-catchfish/assets/48384420/3188b423-c44e-460b-8ca3-be7c446603b7)

**Comment by Unword** [comment]
我知道了，是我的问题，我没了解到需要标签加上那3个符号，才能摘录。
原因是因为下载下来的墨屉，GettingStarted 那里选中不能摘录。
墨屉手册，使用那里我看到的只是添加问号，增加到学习组。
可以关闭这个问题了。谢谢!
